Repository google/gke-policy-automation, pull requests merged in 2022-07, with the labels that each got.

#92 Trigger cluster discover on a project from CLI
  internal/app/app.go
  internal/app/cli.go
Labels: enhancement

#91 Cluster discovery skipped zonal clusters due to name parttern mismatch
  internal/gke/discovery.go
  internal/gke/discovery_test.go
Labels: bug

#88 Limits/test rules
  gke-policies/scalability/limits_configmaps.rego
  gke-policies/scalability/limits_configmaps_test.rego
  gke-policies/scalability/limits_hpas.rego
  gke-policies/scalability/limits_hpas_test.rego
  gke-policies/scalability/limits_unused_hpas.rego
  gke-policies/scalability/limits_unused_hpas_test.rego
Labels: rego

#90 Outputs ng
  README.md
  assets/gke-policy-automation-demo.gif
  internal/app/app.go
  internal/app/app_test.go
  internal/outputs/cloud_storage_collector.go
  internal/outputs/cloud_storage_collector_test.go
  internal/outputs/console_collector.go
  internal/outputs/console_collector_test.go
  internal/outputs/icons.go
  internal/outputs/internal_to_json_mapper.go
  internal/outputs/internal_to_json_mapper_test.go
  internal/outputs/json_collector.go
  internal/outputs/json_collector_test.go
  internal/outputs/output.go
  internal/outputs/pubsub_collector.go
  internal/outputs/pubsub_collector_test.go
  internal/outputs/validation_report.go
  internal/outputs/validation_report_test.go
  internal/outputs/validation_results.go
  internal/policy/policy.go
  internal/policy/policy_test.go
Labels: enhancement

#100 Security Command Center integration
  gke-policies/policy/cluster_binary_authorization.rego
  gke-policies/policy/cluster_maintenance_window.rego
  gke-policies/policy/cluster_receive_updates.rego
  gke-policies/policy/cluster_release_channels.rego
  gke-policies/policy/control_plane_access.rego
  gke-policies/policy/control_plane_disable_legacy_authorization.rego
  gke-policies/policy/control_plane_endpoint.rego
  gke-policies/policy/control_plane_redundancy.rego
  gke-policies/policy/ilb_subsetting.rego
  gke-policies/policy/network_policies.rego
  gke-policies/policy/node_local_dns_cache.rego
  gke-policies/policy/node_pool_autorepair.rego
  gke-policies/policy/node_pool_autoscaling.rego
  gke-policies/policy/node_pool_autoupgrade.rego
  gke-policies/policy/node_pool_forbid_default_sa.rego
  gke-policies/policy/node_pool_integrity_monitoring.rego
  gke-policies/policy/node_pool_multi_zone.rego
  gke-policies/policy/node_pool_redundancy.rego
  gke-policies/policy/node_pool_use_cos.rego
  gke-policies/policy/private_cluster.rego
  gke-policies/policy/secret_encryption.rego
  gke-policies/policy/shielded_nodes.rego
  gke-policies/policy/vpc_native_cluster.rego
  gke-policies/policy/workload_identity.rego
  gke-policies/scalability/limits_configmaps.rego
  gke-policies/scalability/limits_hpas.rego
  gke-policies/scalability/limits_unused_hpas.rego
  go.mod
  go.sum
  internal/app/app.go
  internal/app/app_scc.go
  internal/app/cli.go
  internal/app/cli_test.go
  internal/config/config.go
  internal/outputs/cloud_storage_collector.go
  internal/outputs/collector.go
  internal/outputs/console_collector.go
  internal/outputs/json_collector.go
  internal/outputs/pubsub_collector.go
  internal/outputs/scc/scc.go
  internal/outputs/scc/scc_test.go
  internal/outputs/scc_collector.go
  internal/outputs/scc_collector_test.go
  internal/policy/policy.go
  internal/policy/policy_test.go
Labels: enhancement
